name: Full Workflow with Mirrors
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    
    steps:
      # 1. 更换系统源
      - name: Replace APT sources
        run: |
          sudo sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
          sudo apt update
          
      # 2. 安装系统依赖
      - name: Install system packages
        run: sudo apt install -y libasound2t64 python3-pip
          
      # 3. 配置Docker镜像
      - name: Configure Docker
        run: |
          echo '{"registry-mirrors": ["https://xxxx.mirror.aliyun.com"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          
      # 4. 安装Python依赖
      - name: Install requirements
        run: pip install -r requirements.txt
          
      # 5. 运行主脚本
      - name: Run main script
        run: python main.py
