name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install core dependencies
        run: |
          pip install lxml[html_clean]  # 关键修复步骤
          pip install lxml_html_clean

      - name: Install project dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Execute main.py
        run: python main.py
