name: Run Python Script Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 10 * * *'  # 每天UTC时间10:00自动运行（对应北京时间18:00）

jobs:
  execute-python:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置超时时间
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 
      with:
        fetch-depth: 1  # 优化克隆深度

    - name: Set up Python 3.13
      uses: actions/setup-python@v5  # 
      with:
        python-version: '3.13'
        cache: 'pip'  # 启用依赖缓存 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 

    - name: Set timezone (Asia/Shanghai)
      if: ${{ !contains(github.event_name, 'pull_request') }}
      run: export TZ='Asia/Shanghai'  # 

    - name: Execute Python script
      run: python src/main.py --env production  # 