”name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 安装系统级依赖（Chromium需要）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1

      # 3. 配置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 5. 安装项目依赖
      - name: Install project dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            playwright install
          fi

      # 6. 执行脚本
      - name: Run Python script
        run: python main.py
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output.md