name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 安装系统级依赖（Chromium需要）
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \      
            libnss3 \                
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpulse0
      # 3. 配置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. 安装Playwright及其浏览器
      - name: Install Playwright and browsers
        run: |
          pip install playwright
          playwright install chromium  # 只安装需要的浏览器（推荐Chromium）

      # 5. 安装项目依赖
      - name: Install project dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      # 6. 执行脚本
      - name: Run Python script
        run: python main.py
